name: PRIMEXARMY OFFICIAL BOT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual start button ke liye

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI

      - name: Compile C Binary
        run: |
          gcc PRIMEXARMY.c -o PRIMEXARMY -pthread
          chmod +x PRIMEXARMY

      - name: Run PRIMEXARMY Bot
        env:
          # GitHub Secrets mein apna token daalna safe rehta hai
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
        run: |
          python PRIMEXARMY.py
